# Generated by Django 5.0.2 on 2024-02-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=100, null=True)),
                ('password', models.TextField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
